trigger: none
pr: none
jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: popkeyin_Test
    resourceType: virtualMachine
    resourceName: hkcyz6ljte
  strategy:
    runOnce:
      deploy:
          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  pwd
                  docker stop booking_page || true
                  docker rm booking_page || true
                  docker rmi registry.digitalocean.com/popkey-repo/booking_page || true
            - task: Docker@2
              displayName: 'Run Docker command'
              inputs:
                containerRegistry: 'docker_SC'
                command: 'run'
                arguments: '-d -p 8090:80 --name booking_page registry.digitalocean.com/popkey-repo/booking_page:latest'